server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lhy0707/demodb.git #GitHub上面的git仓库名字


